version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_app
    volumes: 
      - ./:/var/www
    depends_on:
      - db
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public 
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 939615
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
